name: C/C++ CI

on: [push]


jobs:
  job_id:
     runs-on: ubuntu-latest
     name: foobar
     steps:
       - name: Checkout
         uses: actions/checkout@v1
       - name: configure
         run: |
           env
           whoami
