name: C/C++ CI

on: [push]

env:
  autopull:  0

jobs:
  flow123d:
     runs-on: ubuntu-latest
     name: Flow123d debug
     
     steps:
       - uses: actions/checkout@v1
       - name: Configure
         run: bin/fterm --no-term exec make -j2
           
       - name: Verify compilation
         run: bin/fterm --no-term run --version
         continue-on-error: false

       - name: Test - 01_cmd_line
         run: bin/fterm --no-term exec tests/runtest tests/01_cmd_line
         continue-on-error: true

       - name: Test - 02_generic_input
         run: bin/fterm --no-term exec tests/runtest tests/02_generic_input
         continue-on-error: true

       - name: Test - 03_generic_output
         run: bin/fterm --no-term exec tests/runtest tests/03_generic_output
         continue-on-error: true

       - name: Test - 04_generic_mesh
         run: bin/fterm --no-term exec tests/runtest tests/04_generic_mesh
         continue-on-error: true

       - name: Test - 05_tutorial
         run: bin/fterm --no-term exec tests/runtest tests/05_tutorial
         continue-on-error: true

       - name: Test - 06_errors
         run: bin/fterm --no-term exec tests/runtest tests/06_errors
         continue-on-error: true

       - name: Test - 10_darcy
         run: bin/fterm --no-term exec tests/runtest tests/10_darcy
         continue-on-error: true

       - name: Test - 11_darcy_bc
         run: bin/fterm --no-term exec tests/runtest tests/11_darcy_bc
         continue-on-error: true

       - name: Test - 12_darcy_frac
         run: bin/fterm --no-term exec tests/runtest tests/12_darcy_frac
         continue-on-error: true

       - name: Test - 13_darcy_time
         run: bin/fterm --no-term exec tests/runtest tests/13_darcy_time
         continue-on-error: true

       - name: Test - 14_darcy_richards
         run: bin/fterm --no-term exec tests/runtest tests/14_darcy_richards
         continue-on-error: true

       - name: Test - 20_solute_fv
         run: bin/fterm --no-term exec tests/runtest tests/20_solute_fv
         continue-on-error: true

       - name: Test - 21_solute_fv_frac
         run: bin/fterm --no-term exec tests/runtest tests/21_solute_fv_frac
         continue-on-error: true

       - name: Test - 22_solute_fv_time
         run: bin/fterm --no-term exec tests/runtest tests/22_solute_fv_time
         continue-on-error: true

       - name: Test - 24_solute_dg
         run: bin/fterm --no-term exec tests/runtest tests/24_solute_dg
         continue-on-error: true

       - name: Test - 25_solute_dg_bc
         run: bin/fterm --no-term exec tests/runtest tests/25_solute_dg_bc
         continue-on-error: true

       - name: Test - 26_solute_dg_frac
         run: bin/fterm --no-term exec tests/runtest tests/26_solute_dg_frac
         continue-on-error: true

       - name: Test - 27_solute_dg_time
         run: bin/fterm --no-term exec tests/runtest tests/27_solute_dg_time
         continue-on-error: true

       - name: Test - 30_sorption
         run: bin/fterm --no-term exec tests/runtest tests/30_sorption
         continue-on-error: true

       - name: Test - 31_dual_por
         run: bin/fterm --no-term exec tests/runtest tests/31_dual_por
         continue-on-error: true

       - name: Test - 32_decay
         run: bin/fterm --no-term exec tests/runtest tests/32_decay
         continue-on-error: true

       - name: Test - 33_reaction
         run: bin/fterm --no-term exec tests/runtest tests/33_reaction
         continue-on-error: true

       - name: Test - 34_sorption_dg
         run: bin/fterm --no-term exec tests/runtest tests/34_sorption_dg
         continue-on-error: true

       - name: Test - 40_heat
         run: bin/fterm --no-term exec tests/runtest tests/40_heat
         continue-on-error: true
