name: C/C++ CI

on: [push]


jobs:
  job_id:
     runs-on: ubuntu-latest
     name: foobar
     steps:
       - name: configure
         run: |
           env
           whoami
           ls -la
           docker --version
           docker run hello-world
           
